### PR TITLE
Run package installer as part of SWAG init to prevent init fail due to missing dns plugin

### LINKED ISSUE #445: [BUG] Certbot Plugins never run when a custom DNSPLUGIN is chosen
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Progress stops at "Please set the DNSPLUGIN variable to one of the following:". The certbot-dns-\<plugin\> is never installed.

### Expected Behavior

The certbot-dns-\<plugin\> should be installed.

### Steps To Reproduce

Run SWAG with:
DNSPLUGIN=glesys
DOCKER_MODS=linuxserver/mods:universal-package-install
INSTALL_PIP_PACKAGES=certbot-dns-glesys

### Environment

```markdown
- OS: Ubuntu
- How docker service was installed: https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
```

### CPU architecture

x86-64

### Docker creation

```bash
---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=yourdomain.se
      - VALIDATION=dns
      - SUBDOMAINS=www, #optional
      - CERTPROVIDER= #optional
      - DNSPLUGIN=glesys
      - PROPAGATION= #optional
      - EMAIL= #optional
      - ONLY_SUBDOMAINS=true #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - DOCKER_MODS_DEBUG=true
      - INSTALL_PIP_PACKAGES=certbot-dns-glesys
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
```

### Container logs

```bash
swag  | [mod-init] Running in debug mode
swag  | [mod-init] Attempting to run Docker Modification Logic
swag  | [mod-init] Adding linuxserver/mods:universal-package-install to container
swag  | Note: Unnecessary use of -X or --request, GET is already inferred.
swag  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
swag  |                                  Dload  Upload   Total   Spent    Left  Speed
swag  | 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host ghcr.io:443 was resolved.
swag  | * IPv6: (none)
swag  | * IPv4: 140.82.121.33
swag  | *   Trying 140.82.121.33:443...
swag  | * Connected to ghcr.io (140.82.121.33) port 443
swag  | * ALPN: curl offers h2,http/1.1
swag  | } [5 bytes data]
swag  | * TLSv1.3 (OUT), TLS handshake, Client hello (1):
swag  | } [512 bytes data]
swag  | *  CAfile: /etc/ssl/certs/ca-certificates.crt
swag  | *  CApath: /etc/ssl/certs
swag  | { [5 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Server hello (2):
swag  | { [122 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
swag  | { [19 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Certificate (11):
swag  | { [3256 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, CERT verify (15):
swag  | { [520 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Finished (20):
swag  | { [36 bytes data]
swag  | * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
swag  | } [1 bytes data]
swag  | * TLSv1.3 (OUT), TLS handshake, Finished (20):
swag  | } [36 bytes data]
swag  | * SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256 / X25519 / RSASSA-PSS
swag  | * ALPN: server accepted h2
swag  | * Server certificate:
swag  | *  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.ghcr.io
swag  | *  start date: Jul 10 00:00:00 2023 GMT
swag  | *  expire date: Jul  9 23:59:59 2024 GMT
swag  | *  subjectAltName: host "ghcr.io" matched cert's "ghcr.io"
swag  | *  issuer: C=US; O=DigiCert Inc; CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1
swag  | *  SSL certificate verify ok.
swag  | *   Certificate level 0: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
swag  | *   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
swag  | *   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
swag  | } [5 bytes data]
swag  | * using HTTP/2
swag  | * [HTTP/2] [1] OPENED stream for https://ghcr.io/token?scope=repository%3Alinuxserver%2Fmods%3Apull
swag  | * [HTTP/2] [1] [:method: GET]
swag  | * [HTTP/2] [1] [:scheme: https]
swag  | * [HTTP/2] [1] [:authority: ghcr.io]
swag  | * [HTTP/2] [1] [:path: /token?scope=repository%3Alinuxserver%2Fmods%3Apull]
swag  | * [HTTP/2] [1] [user-agent: curl/8.5.0]
swag  | * [HTTP/2] [1] [accept: */*]
swag  | } [5 bytes data]
swag  | > GET /token?scope=repository%3Alinuxserver%2Fmods%3Apull HTTP/2
swag  | > Host: ghcr.io
swag  | > User-Agent: curl/8.5.0
swag  | > Accept: */*
swag  | > 
swag  | { [5 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
swag  | { [57 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
swag  | { [57 bytes data]
swag  | * old SSL session ID is stale, removing
swag  | { [5 bytes data]
swag  | < HTTP/2 200 
swag  | < content-type: application/json
swag  | < docker-distribution-api-version: registry/2.0
swag  | < date: Tue, 02 Jan 2024 18:51:05 GMT
swag  | < content-length: 65
swag  | < x-github-request-id: 7ACF:29F831:6537749:67878F8:65945B19
swag  | < 
swag  | { [65 bytes data]
swag  | 
100    65  100    65    0     0    243      0 --:--:-- --:--:-- --:--:--   244
swag  | * Connection #0 to host ghcr.io left intact
swag  | [mod-init] Using https://ghcr.io/token?scope=repository%3Alinuxserver%2Fmods%3Apull as auth endpoint
swag  | Note: Unnecessary use of -X or --request, GET is already inferred.
swag  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
swag  |                                  Dload  Upload   Total   Spent    Left  Speed
swag  | 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host lscr.io:443 was resolved.
swag  | * IPv6: (none)
swag  | * IPv4: 3.77.103.135, 3.67.33.93
swag  | *   Trying 3.77.103.135:443...
swag  | * Connected to lscr.io (3.77.103.135) port 443
swag  | * ALPN: curl offers h2,http/1.1
swag  | } [5 bytes data]
swag  | * TLSv1.3 (OUT), TLS handshake, Client hello (1):
swag  | } [512 bytes data]
swag  | *  CAfile: /etc/ssl/certs/ca-certificates.crt
swag  | *  CApath: /etc/ssl/certs
swag  | { [5 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Server hello (2):
swag  | { [122 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
swag  | { [19 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Certificate (11):
swag  | { [3957 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, CERT verify (15):
swag  | { [264 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Finished (20):
swag  | { [52 bytes data]
swag  | * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
swag  | } [1 bytes data]
swag  | * TLSv1.3 (OUT), TLS handshake, Finished (20):
swag  | } [52 bytes data]
swag  | * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / RSASSA-PSS
swag  | * ALPN: server accepted h2
swag  | * Server certificate:
swag  | *  subject: CN=lscr.io
swag  | *  start date: Nov 14 00:29:23 2023 GMT
swag  | *  expire date: Feb 12 00:29:22 2024 GMT
swag  | *  subjectAltName: host "lscr.io" matched cert's "lscr.io"
swag  | *  issuer: C=US; O=Let's Encrypt; CN=R3
swag  | *  SSL certificate verify ok.
swag  | *   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
swag  | *   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
swag  | *   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
swag  | } [5 bytes data]
swag  | * using HTTP/2
swag  | * [HTTP/2] [1] OPENED stream for https://lscr.io/v2/linuxserver/mods/manifests/universal-package-install
swag  | * [HTTP/2] [1] [:method: GET]
swag  | * [HTTP/2] [1] [:scheme: https]
swag  | * [HTTP/2] [1] [:authority: lscr.io]
swag  | * [HTTP/2] [1] [:path: /v2/linuxserver/mods/manifests/universal-package-install]
swag  | * [HTTP/2] [1] [user-agent: Mozilla/5.0 (Linux x86_64) linuxserver.io lscr.io/linuxserver/mods:universal-package-install]
swag  | * [HTTP/2] [1] [accept: application/vnd.docker.distribution.manifest.v2+json]
swag  | * [HTTP/2] [1] [accept: application/vnd.oci.image.index.v1+json]
swag  | * [HTTP/2] [1] [authorization: Bearer djE6bGludXhzZXJ2ZXIvbW9kczoxNzA0MjIxNDY1Njc5MDgyMjY1]
swag  | } [5 bytes data]
swag  | > GET /v2/linuxserver/mods/manifests/universal-package-install HTTP/2
swag  | > Host: lscr.io
swag  | > User-Agent: Mozilla/5.0 (Linux x86_64) linuxserver.io lscr.io/linuxserver/mods:universal-package-install
swag  | > Accept: application/vnd.docker.distribution.manifest.v2+json
swag  | > Accept: application/vnd.oci.image.index.v1+json
swag  | > Authorization: Bearer djE6bGludXhzZXJ2ZXIvbW9kczoxNzA0MjIxNDY1Njc5MDgyMjY1
swag  | > 
swag  | { [5 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
swag  | { [57 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
swag  | { [57 bytes data]
swag  | * old SSL session ID is stale, removing
swag  | { [5 bytes data]
swag  | < HTTP/2 200 
swag  | < date: Tue, 02 Jan 2024 18:51:06 GMT
swag  | < content-type: application/vnd.docker.distribution.manifest.v2+json
swag  | < content-length: 523
swag  | < docker-content-digest: sha256:0cd756cfff97445eaaaeeab536b6357e57177c8cb8e2c444d88196853a265fd8
swag  | < docker-distribution-api-version: registry/2.0
swag  | < etag: "sha256:0cd756cfff97445eaaaeeab536b6357e57177c8cb8e2c444d88196853a265fd8"
swag  | < x-github-request-id: 87B4:34B2DF:6A96DD:6D0E07:65945B1A
swag  | < strict-transport-security: max-age=15724800; includeSubDomains
swag  | < 
swag  | { [523 bytes data]
swag  | 
100   523  100   523    0     0   2233      0 --:--:-- --:--:-- --:--:--  2225
100   523  100   523    0     0   2233      0 --:--:-- --:--:-- --:--:--  2225
swag  | * Connection #0 to host lscr.io left intact
swag  | Note: Unnecessary use of -X or --request, GET is already inferred.
swag  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
swag  |                                  Dload  Upload   Total   Spent    Left  Speed
swag  | 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host lscr.io:443 was resolved.
swag  | * IPv6: (none)
swag  | * IPv4: 3.67.33.93, 3.77.103.135
swag  | *   Trying 3.67.33.93:443...
swag  | * Connected to lscr.io (3.67.33.93) port 443
swag  | * ALPN: curl offers h2,http/1.1
swag  | } [5 bytes data]
swag  | * TLSv1.3 (OUT), TLS handshake, Client hello (1):
swag  | } [512 bytes data]
swag  | *  CAfile: /etc/ssl/certs/ca-certificates.crt
swag  | *  CApath: /etc/ssl/certs
swag  | { [5 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Server hello (2):
swag  | { [122 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
swag  | { [19 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Certificate (11):
swag  | { [3957 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, CERT verify (15):
swag  | { [264 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Finished (20):
swag  | { [52 bytes data]
swag  | * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
swag  | } [1 bytes data]
swag  | * TLSv1.3 (OUT), TLS handshake, Finished (20):
swag  | } [52 bytes data]
swag  | * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / RSASSA-PSS
swag  | * ALPN: server accepted h2
swag  | * Server certificate:
swag  | *  subject: CN=lscr.io
swag  | *  start date: Nov 14 00:29:23 2023 GMT
swag  | *  expire date: Feb 12 00:29:22 2024 GMT
swag  | *  subjectAltName: host "lscr.io" matched cert's "lscr.io"
swag  | *  issuer: C=US; O=Let's Encrypt; CN=R3
swag  | *  SSL certificate verify ok.
swag  | *   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
swag  | *   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
swag  | *   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
swag  | } [5 bytes data]
swag  | * using HTTP/2
swag  | * [HTTP/2] [1] OPENED stream for https://lscr.io/v2/linuxserver/mods/manifests/universal-package-install
swag  | * [HTTP/2] [1] [:method: GET]
swag  | * [HTTP/2] [1] [:scheme: https]
swag  | * [HTTP/2] [1] [:authority: lscr.io]
swag  | * [HTTP/2] [1] [:path: /v2/linuxserver/mods/manifests/universal-package-install]
swag  | * [HTTP/2] [1] [user-agent: Mozilla/5.0 (Linux x86_64) linuxserver.io lscr.io/linuxserver/mods:universal-package-install]
swag  | * [HTTP/2] [1] [accept: application/vnd.docker.distribution.manifest.v2+json]
swag  | * [HTTP/2] [1] [accept: application/vnd.oci.image.manifest.v1+json]
swag  | * [HTTP/2] [1] [authorization: Bearer djE6bGludXhzZXJ2ZXIvbW9kczoxNzA0MjIxNDY1Njc5MDgyMjY1]
swag  | } [5 bytes data]
swag  | > GET /v2/linuxserver/mods/manifests/universal-package-install HTTP/2
swag  | > Host: lscr.io
swag  | > User-Agent: Mozilla/5.0 (Linux x86_64) linuxserver.io lscr.io/linuxserver/mods:universal-package-install
swag  | > Accept: application/vnd.docker.distribution.manifest.v2+json
swag  | > Accept: application/vnd.oci.image.manifest.v1+json
swag  | > Authorization: Bearer djE6bGludXhzZXJ2ZXIvbW9kczoxNzA0MjIxNDY1Njc5MDgyMjY1
swag  | > 
swag  | { [5 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
swag  | { [57 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
swag  | { [57 bytes data]
swag  | * old SSL session ID is stale, removing
swag  | { [5 bytes data]
swag  | < HTTP/2 200 
swag  | < date: Tue, 02 Jan 2024 18:51:06 GMT
swag  | < content-type: application/vnd.docker.distribution.manifest.v2+json
swag  | < content-length: 523
swag  | < docker-content-digest: sha256:0cd756cfff97445eaaaeeab536b6357e57177c8cb8e2c444d88196853a265fd8
swag  | < docker-distribution-api-version: registry/2.0
swag  | < etag: "sha256:0cd756cfff97445eaaaeeab536b6357e57177c8cb8e2c444d88196853a265fd8"
swag  | < x-github-request-id: 890A:216EBD:FF8D65:106063D:65945B1A
swag  | < strict-transport-security: max-age=15724800; includeSubDomains
swag  | < 
swag  | { [523 bytes data]
swag  | 
100   523  100   523    0     0   1967      0 --:--:-- --:--:-- --:--:--  1973
swag  | * Connection #0 to host lscr.io left intact
swag  | [mod-init] Downloading linuxserver/mods:universal-package-install from lscr.io
swag  | Note: Unnecessary use of -X or --request, GET is already inferred.
swag  |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
swag  |                                  Dload  Upload   Total   Spent    Left  Speed
swag  | 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host lscr.io:443 was resolved.
swag  | * IPv6: (none)
swag  | * IPv4: 3.77.103.135, 3.67.33.93
swag  | *   Trying 3.77.103.135:443...
swag  | * Connected to lscr.io (3.77.103.135) port 443
swag  | * ALPN: curl offers h2,http/1.1
swag  | } [5 bytes data]
swag  | * TLSv1.3 (OUT), TLS handshake, Client hello (1):
swag  | } [512 bytes data]
swag  | *  CAfile: /etc/ssl/certs/ca-certificates.crt
swag  | *  CApath: /etc/ssl/certs
swag  | { [5 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Server hello (2):
swag  | { [122 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
swag  | { [19 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Certificate (11):
swag  | { [3957 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, CERT verify (15):
swag  | { [264 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Finished (20):
swag  | { [52 bytes data]
swag  | * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
swag  | } [1 bytes data]
swag  | * TLSv1.3 (OUT), TLS handshake, Finished (20):
swag  | } [52 bytes data]
swag  | * SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / RSASSA-PSS
swag  | * ALPN: server accepted h2
swag  | * Server certificate:
swag  | *  subject: CN=lscr.io
swag  | *  start date: Nov 14 00:29:23 2023 GMT
swag  | *  expire date: Feb 12 00:29:22 2024 GMT
swag  | *  subjectAltName: host "lscr.io" matched cert's "lscr.io"
swag  | *  issuer: C=US; O=Let's Encrypt; CN=R3
swag  | *  SSL certificate verify ok.
swag  | *   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
swag  | *   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
swag  | *   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
swag  | } [5 bytes data]
swag  | * using HTTP/2
swag  | * [HTTP/2] [1] OPENED stream for https://lscr.io/v2/linuxserver/mods/blobs/sha256:179666823e425c84f903183aa0b76eb4fe6ce386fdeb55ca85b56b7791669140
swag  | * [HTTP/2] [1] [:method: GET]
swag  | * [HTTP/2] [1] [:scheme: https]
swag  | * [HTTP/2] [1] [:authority: lscr.io]
swag  | * [HTTP/2] [1] [:path: /v2/linuxserver/mods/blobs/sha256:179666823e425c84f903183aa0b76eb4fe6ce386fdeb55ca85b56b7791669140]
swag  | * [HTTP/2] [1] [user-agent: Mozilla/5.0 (Linux x86_64) linuxserver.io lscr.io/linuxserver/mods:universal-package-install]
swag  | * [HTTP/2] [1] [accept: */*]
swag  | * [HTTP/2] [1] [authorization: Bearer djE6bGludXhzZXJ2ZXIvbW9kczoxNzA0MjIxNDY1Njc5MDgyMjY1]
swag  | } [5 bytes data]
swag  | > GET /v2/linuxserver/mods/blobs/sha256:179666823e425c84f903183aa0b76eb4fe6ce386fdeb55ca85b56b7791669140 HTTP/2
swag  | > Host: lscr.io
swag  | > User-Agent: Mozilla/5.0 (Linux x86_64) linuxserver.io lscr.io/linuxserver/mods:universal-package-install
swag  | > Accept: */*
swag  | > Authorization: Bearer djE6bGludXhzZXJ2ZXIvbW9kczoxNzA0MjIxNDY1Njc5MDgyMjY1
swag  | > 
swag  | { [5 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
swag  | { [57 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
swag  | { [57 bytes data]
swag  | * old SSL session ID is stale, removing
swag  | { [5 bytes data]
swag  | < HTTP/2 307 
swag  | < date: Tue, 02 Jan 2024 18:51:06 GMT
swag  | < content-type: application/x-gzip
swag  | < content-length: 0
swag  | < location: https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:179666823e425c84f903183aa0b76eb4fe6ce386fdeb55ca85b56b7791669140?se=2024-01-02T19%3A00%3A00Z&sig=ldNkboSEGwUFFpD0Qf9nNDDVYefYznFDtVtxpC93m4M%3D&sp=r&spr=https&sr=b&sv=2019-12-12
swag  | < docker-distribution-api-version: registry/2.0
swag  | < x-github-request-id: 73D8:D2EDF:579E246:59BE68C:65945B1A
swag  | < strict-transport-security: max-age=15724800; includeSubDomains
swag  | < 
swag  | 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
swag  | * Connection #0 to host lscr.io left intact
swag  | * Issue another request to this URL: 'https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:179666823e425c84f903183aa0b76eb4fe6ce386fdeb55ca85b56b7791669140?se=2024-01-02T19%3A00%3A00Z&sig=ldNkboSEGwUFFpD0Qf9nNDDVYefYznFDtVtxpC93m4M%3D&sp=r&spr=https&sr=b&sv=2019-12-12'
swag  | * Host pkg-containers.githubusercontent.com:443 was resolved.
swag  | * IPv6: 2606:50c0:8003::154, 2606:50c0:8000::154, 2606:50c0:8001::154, 2606:50c0:8002::154
swag  | * IPv4: 185.199.108.154, 185.199.109.154, 185.199.111.154, 185.199.110.154
swag  | *   Trying 185.199.108.154:443...
swag  | * Connected to pkg-containers.githubusercontent.com (185.199.108.154) port 443
swag  | * ALPN: curl offers h2,http/1.1
swag  | } [5 bytes data]
swag  | * TLSv1.3 (OUT), TLS handshake, Client hello (1):
swag  | } [512 bytes data]
swag  | *  CAfile: /etc/ssl/certs/ca-certificates.crt
swag  | *  CApath: /etc/ssl/certs
swag  | { [5 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Server hello (2):
swag  | { [122 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
swag  | { [19 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Certificate (11):
swag  | { [3050 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, CERT verify (15):
swag  | { [264 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Finished (20):
swag  | { [36 bytes data]
swag  | * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
swag  | } [1 bytes data]
swag  | * TLSv1.3 (OUT), TLS handshake, Finished (20):
swag  | } [36 bytes data]
swag  | * SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256 / X25519 / RSASSA-PSS
swag  | * ALPN: server accepted h2
swag  | * Server certificate:
swag  | *  subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=*.github.io
swag  | *  start date: Feb 21 00:00:00 2023 GMT
swag  | *  expire date: Mar 20 23:59:59 2024 GMT
swag  | *  subjectAltName: host "pkg-containers.githubusercontent.com" matched cert's "*.githubusercontent.com"
swag  | *  issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS RSA SHA256 2020 CA1
swag  | *  SSL certificate verify ok.
swag  | *   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
swag  | *   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
swag  | *   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha1WithRSAEncryption
swag  | { [5 bytes data]
swag  | * TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
swag  | { [193 bytes data]
swag  | * using HTTP/2
swag  | * [HTTP/2] [1] OPENED stream for https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:179666823e425c84f903183aa0b76eb4fe6ce386fdeb55ca85b56b7791669140?se=2024-01-02T19%3A00%3A00Z&sig=ldNkboSEGwUFFpD0Qf9nNDDVYefYznFDtVtxpC93m4M%3D&sp=r&spr=https&sr=b&sv=2019-12-12
swag  | * [HTTP/2] [1] [:method: GET]
swag  | * [HTTP/2] [1] [:scheme: https]
swag  | * [HTTP/2] [1] [:authority: pkg-containers.githubusercontent.com]
swag  | * [HTTP/2] [1] [:path: /ghcr1/blobs/sha256:179666823e425c84f903183aa0b76eb4fe6ce386fdeb55ca85b56b7791669140?se=2024-01-02T19%3A00%3A00Z&sig=ldNkboSEGwUFFpD0Qf9nNDDVYefYznFDtVtxpC93m4M%3D&sp=r&spr=https&sr=b&sv=2019-12-12]
swag  | * [HTTP/2] [1] [user-agent: Mozilla/5.0 (Linux x86_64) linuxserver.io lscr.io/linuxserver/mods:universal-package-install]
swag  | * [HTTP/2] [1] [accept: */*]
swag  | } [5 bytes data]
swag  | > GET /ghcr1/blobs/sha256:179666823e425c84f903183aa0b76eb4fe6ce386fdeb55ca85b56b7791669140?se=2024-01-02T19%3A00%3A00Z&sig=ldNkboSEGwUFFpD0Qf9nNDDVYefYznFDtVtxpC93m4M%3D&sp=r&spr=https&sr=b&sv=2019-12-12 HTTP/2
swag  | > Host: pkg-containers.githubusercontent.com
swag  | > User-Agent: Mozilla/5.0 (Linux x86_64) linuxserver.io lscr.io/linuxserver/mods:universal-package-install
swag  | > Accept: */*
swag  | > 
swag  | { [5 bytes data]
swag  | < HTTP/2 200 
swag  | < content-type: application/x-gzip
swag  | < last-modified: Sat, 20 May 2023 13:16:36 GMT
swag  | < etag: "0x8DB593470489E9F"
swag  | < server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
swag  | < x-ms-request-id: d68ae6eb-f01e-00bf-4fac-3df2c3000000
swag  | < x-ms-version: 2019-12-12
swag  | < x-ms-creation-time: Sat, 20 May 2023 13:16:36 GMT
swag  | < x-ms-lease-status: unlocked
swag  | < x-ms-lease-state: available
swag  | < x-ms-blob-type: BlockBlob
swag  | < x-ms-copy-id: 1b8e39cc-c77d-453a-97f9-7592047ade98
swag  | < x-ms-copy-status: success
swag  | < x-ms-copy-progress: 771/771
swag  | < x-ms-copy-completion-time: Sat, 20 May 2023 13:16:36 GMT
swag  | < content-disposition: 
swag  | < x-ms-server-encrypted: true
swag  | < via: 1.1 varnish, 1.1 varnish
swag  | < accept-ranges: bytes
swag  | < date: Tue, 02 Jan 2024 18:51:06 GMT
swag  | < age: 0
swag  | < x-served-by: cache-iad-kjyo7100157-IAD, cache-bma1661-BMA
swag  | < x-cache: MISS, MISS
swag  | < x-cache-hits: 0, 0
swag  | < strict-transport-security: max-age=31536000
swag  | < x-fastly-request-id: 0c2edb3b119c74286b15e1d2a239b2ddfca034e0
swag  | < content-length: 771
swag  | < 
swag  | { [771 bytes data]
swag  | 
100   771  100   771    0     0   2028      0 --:--:-- --:--:-- --:--:--  2028
swag  | * Connection #1 to host pkg-containers.githubusercontent.com left intact
swag  | [mod-init] Installing linuxserver/mods:universal-package-install
swag  | [mod-init] linuxserver/mods:universal-package-install applied to container
swag  | [migrations] started
swag  | [migrations] 01-nginx-site-confs-default: skipped
swag  | [migrations] done
swag  | ───────────────────────────────────────
swag  | 
swag  |       ██╗     ███████╗██╗ ██████╗ 
swag  |       ██║     ██╔════╝██║██╔═══██╗
swag  |       ██║     ███████╗██║██║   ██║
swag  |       ██║     ╚════██║██║██║   ██║
swag  |       ███████╗███████║██║╚██████╔╝
swag  |       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
swag  | 
swag  |    Brought to you by linuxserver.io
swag  | ───────────────────────────────────────
swag  | 
swag  | To support the app dev(s) visit:
swag  | Certbot: https://supporters.eff.org/donate/support-work-on-certbot
swag  | 
swag  | To support LSIO projects visit:
swag  | https://www.linuxserver.io/donate/
swag  | 
swag  | ───────────────────────────────────────
swag  | GID/UID
swag  | ───────────────────────────────────────
swag  | 
swag  | User UID:    1000
swag  | User GID:    1000
swag  | ───────────────────────────────────────
swag  | 
swag  | using keys found in /config/keys
swag  | chown: cannot dereference '/config/keys/letsencrypt': No such file or directory
swag  | **** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****
swag  | **** The app may not work properly and we will not provide support for it. ****
swag  | Variables set:
swag  | PUID=1000
swag  | PGID=1000
swag  | TZ=Etc/UTC
swag  | URL=yourdomain.se
swag  | SUBDOMAINS=www,
swag  | EXTRA_DOMAINS=
swag  | ONLY_SUBDOMAINS=true
swag  | VALIDATION=dns
swag  | CERTPROVIDER=
swag  | DNSPLUGIN=glesys
swag  | EMAIL=
swag  | STAGING=false
swag  | 
swag  | Please set the DNSPLUGIN variable to one of the following:
swag  | acmedns
swag  | aliyun
swag  | azure
swag  | bunny
swag  | cloudflare
swag  | cpanel
swag  | desec
swag  | digitalocean
swag  | directadmin
swag  | dnsimple
swag  | dnsmadeeasy
swag  | dnspod
swag  | do
swag  | domeneshop
swag  | dreamhost
swag  | duckdns
swag  | freedns
swag  | gandi
swag  | gehirn
swag  | godaddy
swag  | google
swag  | google-domains
swag  | he
swag  | hetzner
swag  | infomaniak
swag  | inwx
swag  | ionos
swag  | linode
swag  | loopia
swag  | luadns
swag  | namecheap
swag  | netcup
swag  | njalla
swag  | nsone
swag  | ovh
swag  | porkbun
swag  | rfc2136
swag  | route53
swag  | sakuracloud
swag  | standalone
swag  | transip
swag  | vultr
```

### PR DESCRIPTION
**Pull request by aptalca**
closes #445

### CODE REVIEW

File: root/etc/s6-overlay/s6-rc.d/init-certbot-config/run [hunk 1]
```diff
@@ -23,6 +23,13 @@ for i in "${SANED_VARS[@]}"; do
     export echo "${i}"="$(echo "${!i}" | tr '[:upper:]' '[:lower:]')"
 done
 
+# Check for and install requested DNS plugins
+if grep -q "universal-package-install" <<< "${DOCKER_MODS}" && grep -q "certbot-dns" <<< "${INSTALL_PIP_PACKAGES}"; then
+    echo "**** Installing requested dns plugins ****"
+    /etc/s6-overlay/s6-rc.d/init-mod-universal-package-install-add-package/run
+    /etc/s6-overlay/s6-rc.d/init-mods-package-install/run
```
Comment (nemchik) [inline root/etc/s6-overlay/s6-rc.d/init-certbot-config/run:30]:
```suggestion
    /etc/s6-overlay/s6-rc.d/init-mod-universal-package-install-add-package/run
    /etc/s6-overlay/s6-rc.d/init-mods-package-install/run
    echo "#!/usr/bin/with-contenv bash" >/etc/s6-overlay/s6-rc.d/init-mod-universal-package-install-add-package/run
    echo "#!/usr/bin/with-contenv bash" >/etc/s6-overlay/s6-rc.d/init-mods-package-install/run
```
Replacing the `run` scripts with empty (shebang only) files after this point would prevent the double run.

**Review by nemchik — CHANGES_REQUESTED** [review]

File: root/etc/s6-overlay/s6-rc.d/init-certbot-config/run (hunk 1 above)
Comment (nemchik) [reply root/etc/s6-overlay/s6-rc.d/init-certbot-config/run:30]: Just tested this change and it breaks when other mods (that run during the normal mod run later in the init) try to add packages to be installed (ex: swag auto reload tries to install inotify) and causes a loop in the init. Going to have to revert https://github.com/linuxserver/docker-swag/pull/460/commits/bf21a51e1079d762b6817e855463c74c1a843aaf and just let it run twice. At least it's tested, sorry for the extra git work.

**Review by nemchik — APPROVED** [review]
